services:
  postgres:
    image: postgres:18
    restart: always
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - postgresql_data:/var/lib/postgresql/data
    env_file: .env

  ldap:
    build:
      context: ./ldap
    restart: always
    env_file: .env
    volumes:
      - ./ldap/data/lib:/var/lib/openldap/openldap-data
      - ./ldap/lloadd:/var/lib/openldap/openldap-lloadd
      - ./ldap/templates:/customized/templates
      - ./ldap/data/customized:/customized/saved-data

  nexus:
    build: ./nexus
    restart: always
    env_file: .env
    environment:
      - LDAP_BIND_PASS=${LDAP_BIND_PASS_NEXUS}
    volumes:
      - ./nexus/data:/nexus-data
    depends_on:
      - ldap

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "8080:80"  # 外部公開
    env_file: .env
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./nginx/log:/var/log/nginx
    depends_on:
      - nexus

  go-dev:
    build: 
      context: ./golang
      dockerfile: ./development.Dockerfile
    env_file: .env
    environment:
      - LDAP_BIND_CN=${LDAP_BIND_CN_GO}
      - LDAP_BIND_PASS=${LDAP_BIND_PASS_GO}
      - IS_DEBUG=true
      - ROOT_DIR_PATH=${PWD}/golang
    ports:
      - "8083:8080"  # 外部ユーザー向け公開ポート
    working_dir: /app
    volumes:
      - ./golang:/app
      - go_home:/root
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - nexus
    command: sleep infinity

  runner:
    build: 
      context: ./golang
      dockerfile: ./runner.Dockerfile
      args:
        - TARGET_NAME=web_app
    restart: always
    env_file: .env
    environment:
      - LDAP_BIND_CN=${LDAP_BIND_CN_GO}
      - LDAP_BIND_PASS=${LDAP_BIND_PASS_GO}
      - ROOT_DIR_PATH=${PWD}/golang
    ports:
      - "8082:8080" # 外部ユーザー向け公開ポート
    volumes:
      - ./golang/public:/app/public
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - nexus
      - postgres

  node:
    image: node:22
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./node:/app
      - ./golang/public:/app/dist
      - node_home:/root
    command: ./build.sh

volumes:
  go_home:
  node_home:
  postgresql_data: