// Code generated by ent, DO NOT EDIT.

package requestedlibrary

import (
	"time"
	"web_app/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldEQ(FieldName, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldEQ(FieldVersion, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldEQ(FieldUpdatedAt, v))
}

// RequestedBy applies equality check predicate on the "requested_by" field. It's identical to RequestedByEQ.
func RequestedBy(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldEQ(FieldRequestedBy, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldContainsFold(FieldName, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldContainsFold(FieldVersion, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldLTE(FieldUpdatedAt, v))
}

// RequestedByEQ applies the EQ predicate on the "requested_by" field.
func RequestedByEQ(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldEQ(FieldRequestedBy, v))
}

// RequestedByNEQ applies the NEQ predicate on the "requested_by" field.
func RequestedByNEQ(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldNEQ(FieldRequestedBy, v))
}

// RequestedByIn applies the In predicate on the "requested_by" field.
func RequestedByIn(vs ...string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldIn(FieldRequestedBy, vs...))
}

// RequestedByNotIn applies the NotIn predicate on the "requested_by" field.
func RequestedByNotIn(vs ...string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldNotIn(FieldRequestedBy, vs...))
}

// RequestedByGT applies the GT predicate on the "requested_by" field.
func RequestedByGT(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldGT(FieldRequestedBy, v))
}

// RequestedByGTE applies the GTE predicate on the "requested_by" field.
func RequestedByGTE(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldGTE(FieldRequestedBy, v))
}

// RequestedByLT applies the LT predicate on the "requested_by" field.
func RequestedByLT(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldLT(FieldRequestedBy, v))
}

// RequestedByLTE applies the LTE predicate on the "requested_by" field.
func RequestedByLTE(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldLTE(FieldRequestedBy, v))
}

// RequestedByContains applies the Contains predicate on the "requested_by" field.
func RequestedByContains(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldContains(FieldRequestedBy, v))
}

// RequestedByHasPrefix applies the HasPrefix predicate on the "requested_by" field.
func RequestedByHasPrefix(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldHasPrefix(FieldRequestedBy, v))
}

// RequestedByHasSuffix applies the HasSuffix predicate on the "requested_by" field.
func RequestedByHasSuffix(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldHasSuffix(FieldRequestedBy, v))
}

// RequestedByEqualFold applies the EqualFold predicate on the "requested_by" field.
func RequestedByEqualFold(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldEqualFold(FieldRequestedBy, v))
}

// RequestedByContainsFold applies the ContainsFold predicate on the "requested_by" field.
func RequestedByContainsFold(v string) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.FieldContainsFold(FieldRequestedBy, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RequestedLibrary) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RequestedLibrary) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RequestedLibrary) predicate.RequestedLibrary {
	return predicate.RequestedLibrary(sql.NotPredicates(p))
}
