// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"web_app/ent/migrate"

	"web_app/ent/group"
	"web_app/ent/requestedlibrary"
	"web_app/ent/savedlibrary"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Group is the client for interacting with the Group builders.
	Group *GroupClient
	// RequestedLibrary is the client for interacting with the RequestedLibrary builders.
	RequestedLibrary *RequestedLibraryClient
	// SavedLibrary is the client for interacting with the SavedLibrary builders.
	SavedLibrary *SavedLibraryClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Group = NewGroupClient(c.config)
	c.RequestedLibrary = NewRequestedLibraryClient(c.config)
	c.SavedLibrary = NewSavedLibraryClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		Group:            NewGroupClient(cfg),
		RequestedLibrary: NewRequestedLibraryClient(cfg),
		SavedLibrary:     NewSavedLibraryClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:              ctx,
		config:           cfg,
		Group:            NewGroupClient(cfg),
		RequestedLibrary: NewRequestedLibraryClient(cfg),
		SavedLibrary:     NewSavedLibraryClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Group.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Group.Use(hooks...)
	c.RequestedLibrary.Use(hooks...)
	c.SavedLibrary.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Group.Intercept(interceptors...)
	c.RequestedLibrary.Intercept(interceptors...)
	c.SavedLibrary.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *GroupMutation:
		return c.Group.mutate(ctx, m)
	case *RequestedLibraryMutation:
		return c.RequestedLibrary.mutate(ctx, m)
	case *SavedLibraryMutation:
		return c.SavedLibrary.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// GroupClient is a client for the Group schema.
type GroupClient struct {
	config
}

// NewGroupClient returns a client for the Group from the given config.
func NewGroupClient(c config) *GroupClient {
	return &GroupClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `group.Hooks(f(g(h())))`.
func (c *GroupClient) Use(hooks ...Hook) {
	c.hooks.Group = append(c.hooks.Group, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `group.Intercept(f(g(h())))`.
func (c *GroupClient) Intercept(interceptors ...Interceptor) {
	c.inters.Group = append(c.inters.Group, interceptors...)
}

// Create returns a builder for creating a Group entity.
func (c *GroupClient) Create() *GroupCreate {
	mutation := newGroupMutation(c.config, OpCreate)
	return &GroupCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Group entities.
func (c *GroupClient) CreateBulk(builders ...*GroupCreate) *GroupCreateBulk {
	return &GroupCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GroupClient) MapCreateBulk(slice any, setFunc func(*GroupCreate, int)) *GroupCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GroupCreateBulk{err: fmt.Errorf("calling to GroupClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GroupCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GroupCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Group.
func (c *GroupClient) Update() *GroupUpdate {
	mutation := newGroupMutation(c.config, OpUpdate)
	return &GroupUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GroupClient) UpdateOne(_m *Group) *GroupUpdateOne {
	mutation := newGroupMutation(c.config, OpUpdateOne, withGroup(_m))
	return &GroupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GroupClient) UpdateOneID(id string) *GroupUpdateOne {
	mutation := newGroupMutation(c.config, OpUpdateOne, withGroupID(id))
	return &GroupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Group.
func (c *GroupClient) Delete() *GroupDelete {
	mutation := newGroupMutation(c.config, OpDelete)
	return &GroupDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GroupClient) DeleteOne(_m *Group) *GroupDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GroupClient) DeleteOneID(id string) *GroupDeleteOne {
	builder := c.Delete().Where(group.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GroupDeleteOne{builder}
}

// Query returns a query builder for Group.
func (c *GroupClient) Query() *GroupQuery {
	return &GroupQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGroup},
		inters: c.Interceptors(),
	}
}

// Get returns a Group entity by its id.
func (c *GroupClient) Get(ctx context.Context, id string) (*Group, error) {
	return c.Query().Where(group.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GroupClient) GetX(ctx context.Context, id string) *Group {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *GroupClient) Hooks() []Hook {
	return c.hooks.Group
}

// Interceptors returns the client interceptors.
func (c *GroupClient) Interceptors() []Interceptor {
	return c.inters.Group
}

func (c *GroupClient) mutate(ctx context.Context, m *GroupMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GroupCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GroupUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GroupUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GroupDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Group mutation op: %q", m.Op())
	}
}

// RequestedLibraryClient is a client for the RequestedLibrary schema.
type RequestedLibraryClient struct {
	config
}

// NewRequestedLibraryClient returns a client for the RequestedLibrary from the given config.
func NewRequestedLibraryClient(c config) *RequestedLibraryClient {
	return &RequestedLibraryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `requestedlibrary.Hooks(f(g(h())))`.
func (c *RequestedLibraryClient) Use(hooks ...Hook) {
	c.hooks.RequestedLibrary = append(c.hooks.RequestedLibrary, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `requestedlibrary.Intercept(f(g(h())))`.
func (c *RequestedLibraryClient) Intercept(interceptors ...Interceptor) {
	c.inters.RequestedLibrary = append(c.inters.RequestedLibrary, interceptors...)
}

// Create returns a builder for creating a RequestedLibrary entity.
func (c *RequestedLibraryClient) Create() *RequestedLibraryCreate {
	mutation := newRequestedLibraryMutation(c.config, OpCreate)
	return &RequestedLibraryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RequestedLibrary entities.
func (c *RequestedLibraryClient) CreateBulk(builders ...*RequestedLibraryCreate) *RequestedLibraryCreateBulk {
	return &RequestedLibraryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RequestedLibraryClient) MapCreateBulk(slice any, setFunc func(*RequestedLibraryCreate, int)) *RequestedLibraryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RequestedLibraryCreateBulk{err: fmt.Errorf("calling to RequestedLibraryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RequestedLibraryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RequestedLibraryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RequestedLibrary.
func (c *RequestedLibraryClient) Update() *RequestedLibraryUpdate {
	mutation := newRequestedLibraryMutation(c.config, OpUpdate)
	return &RequestedLibraryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RequestedLibraryClient) UpdateOne(_m *RequestedLibrary) *RequestedLibraryUpdateOne {
	mutation := newRequestedLibraryMutation(c.config, OpUpdateOne, withRequestedLibrary(_m))
	return &RequestedLibraryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RequestedLibraryClient) UpdateOneID(id string) *RequestedLibraryUpdateOne {
	mutation := newRequestedLibraryMutation(c.config, OpUpdateOne, withRequestedLibraryID(id))
	return &RequestedLibraryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RequestedLibrary.
func (c *RequestedLibraryClient) Delete() *RequestedLibraryDelete {
	mutation := newRequestedLibraryMutation(c.config, OpDelete)
	return &RequestedLibraryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RequestedLibraryClient) DeleteOne(_m *RequestedLibrary) *RequestedLibraryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RequestedLibraryClient) DeleteOneID(id string) *RequestedLibraryDeleteOne {
	builder := c.Delete().Where(requestedlibrary.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RequestedLibraryDeleteOne{builder}
}

// Query returns a query builder for RequestedLibrary.
func (c *RequestedLibraryClient) Query() *RequestedLibraryQuery {
	return &RequestedLibraryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRequestedLibrary},
		inters: c.Interceptors(),
	}
}

// Get returns a RequestedLibrary entity by its id.
func (c *RequestedLibraryClient) Get(ctx context.Context, id string) (*RequestedLibrary, error) {
	return c.Query().Where(requestedlibrary.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RequestedLibraryClient) GetX(ctx context.Context, id string) *RequestedLibrary {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RequestedLibraryClient) Hooks() []Hook {
	return c.hooks.RequestedLibrary
}

// Interceptors returns the client interceptors.
func (c *RequestedLibraryClient) Interceptors() []Interceptor {
	return c.inters.RequestedLibrary
}

func (c *RequestedLibraryClient) mutate(ctx context.Context, m *RequestedLibraryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RequestedLibraryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RequestedLibraryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RequestedLibraryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RequestedLibraryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RequestedLibrary mutation op: %q", m.Op())
	}
}

// SavedLibraryClient is a client for the SavedLibrary schema.
type SavedLibraryClient struct {
	config
}

// NewSavedLibraryClient returns a client for the SavedLibrary from the given config.
func NewSavedLibraryClient(c config) *SavedLibraryClient {
	return &SavedLibraryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `savedlibrary.Hooks(f(g(h())))`.
func (c *SavedLibraryClient) Use(hooks ...Hook) {
	c.hooks.SavedLibrary = append(c.hooks.SavedLibrary, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `savedlibrary.Intercept(f(g(h())))`.
func (c *SavedLibraryClient) Intercept(interceptors ...Interceptor) {
	c.inters.SavedLibrary = append(c.inters.SavedLibrary, interceptors...)
}

// Create returns a builder for creating a SavedLibrary entity.
func (c *SavedLibraryClient) Create() *SavedLibraryCreate {
	mutation := newSavedLibraryMutation(c.config, OpCreate)
	return &SavedLibraryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SavedLibrary entities.
func (c *SavedLibraryClient) CreateBulk(builders ...*SavedLibraryCreate) *SavedLibraryCreateBulk {
	return &SavedLibraryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SavedLibraryClient) MapCreateBulk(slice any, setFunc func(*SavedLibraryCreate, int)) *SavedLibraryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SavedLibraryCreateBulk{err: fmt.Errorf("calling to SavedLibraryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SavedLibraryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SavedLibraryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SavedLibrary.
func (c *SavedLibraryClient) Update() *SavedLibraryUpdate {
	mutation := newSavedLibraryMutation(c.config, OpUpdate)
	return &SavedLibraryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SavedLibraryClient) UpdateOne(_m *SavedLibrary) *SavedLibraryUpdateOne {
	mutation := newSavedLibraryMutation(c.config, OpUpdateOne, withSavedLibrary(_m))
	return &SavedLibraryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SavedLibraryClient) UpdateOneID(id string) *SavedLibraryUpdateOne {
	mutation := newSavedLibraryMutation(c.config, OpUpdateOne, withSavedLibraryID(id))
	return &SavedLibraryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SavedLibrary.
func (c *SavedLibraryClient) Delete() *SavedLibraryDelete {
	mutation := newSavedLibraryMutation(c.config, OpDelete)
	return &SavedLibraryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SavedLibraryClient) DeleteOne(_m *SavedLibrary) *SavedLibraryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SavedLibraryClient) DeleteOneID(id string) *SavedLibraryDeleteOne {
	builder := c.Delete().Where(savedlibrary.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SavedLibraryDeleteOne{builder}
}

// Query returns a query builder for SavedLibrary.
func (c *SavedLibraryClient) Query() *SavedLibraryQuery {
	return &SavedLibraryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSavedLibrary},
		inters: c.Interceptors(),
	}
}

// Get returns a SavedLibrary entity by its id.
func (c *SavedLibraryClient) Get(ctx context.Context, id string) (*SavedLibrary, error) {
	return c.Query().Where(savedlibrary.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SavedLibraryClient) GetX(ctx context.Context, id string) *SavedLibrary {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SavedLibraryClient) Hooks() []Hook {
	return c.hooks.SavedLibrary
}

// Interceptors returns the client interceptors.
func (c *SavedLibraryClient) Interceptors() []Interceptor {
	return c.inters.SavedLibrary
}

func (c *SavedLibraryClient) mutate(ctx context.Context, m *SavedLibraryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SavedLibraryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SavedLibraryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SavedLibraryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SavedLibraryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SavedLibrary mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Group, RequestedLibrary, SavedLibrary []ent.Hook
	}
	inters struct {
		Group, RequestedLibrary, SavedLibrary []ent.Interceptor
	}
)
