// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"
	"web_app/ent/predicate"
	"web_app/ent/requestedlibrary"
	"web_app/ent/savedlibrary"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeRequestedLibrary = "RequestedLibrary"
	TypeSavedLibrary     = "SavedLibrary"
)

// RequestedLibraryMutation represents an operation that mutates the RequestedLibrary nodes in the graph.
type RequestedLibraryMutation struct {
	config
	op            Op
	typ           string
	id            *string
	kind          *string
	version       *string
	status        *string
	created_at    *time.Time
	updated_at    *time.Time
	name          *string
	requested_by  *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*RequestedLibrary, error)
	predicates    []predicate.RequestedLibrary
}

var _ ent.Mutation = (*RequestedLibraryMutation)(nil)

// requestedlibraryOption allows management of the mutation configuration using functional options.
type requestedlibraryOption func(*RequestedLibraryMutation)

// newRequestedLibraryMutation creates new mutation for the RequestedLibrary entity.
func newRequestedLibraryMutation(c config, op Op, opts ...requestedlibraryOption) *RequestedLibraryMutation {
	m := &RequestedLibraryMutation{
		config:        c,
		op:            op,
		typ:           TypeRequestedLibrary,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRequestedLibraryID sets the ID field of the mutation.
func withRequestedLibraryID(id string) requestedlibraryOption {
	return func(m *RequestedLibraryMutation) {
		var (
			err   error
			once  sync.Once
			value *RequestedLibrary
		)
		m.oldValue = func(ctx context.Context) (*RequestedLibrary, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().RequestedLibrary.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRequestedLibrary sets the old RequestedLibrary of the mutation.
func withRequestedLibrary(node *RequestedLibrary) requestedlibraryOption {
	return func(m *RequestedLibraryMutation) {
		m.oldValue = func(context.Context) (*RequestedLibrary, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RequestedLibraryMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RequestedLibraryMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of RequestedLibrary entities.
func (m *RequestedLibraryMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RequestedLibraryMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *RequestedLibraryMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().RequestedLibrary.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetKind sets the "kind" field.
func (m *RequestedLibraryMutation) SetKind(s string) {
	m.kind = &s
}

// Kind returns the value of the "kind" field in the mutation.
func (m *RequestedLibraryMutation) Kind() (r string, exists bool) {
	v := m.kind
	if v == nil {
		return
	}
	return *v, true
}

// OldKind returns the old "kind" field's value of the RequestedLibrary entity.
// If the RequestedLibrary object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestedLibraryMutation) OldKind(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldKind is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldKind requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldKind: %w", err)
	}
	return oldValue.Kind, nil
}

// ResetKind resets all changes to the "kind" field.
func (m *RequestedLibraryMutation) ResetKind() {
	m.kind = nil
}

// SetVersion sets the "version" field.
func (m *RequestedLibraryMutation) SetVersion(s string) {
	m.version = &s
}

// Version returns the value of the "version" field in the mutation.
func (m *RequestedLibraryMutation) Version() (r string, exists bool) {
	v := m.version
	if v == nil {
		return
	}
	return *v, true
}

// OldVersion returns the old "version" field's value of the RequestedLibrary entity.
// If the RequestedLibrary object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestedLibraryMutation) OldVersion(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldVersion is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldVersion requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldVersion: %w", err)
	}
	return oldValue.Version, nil
}

// ResetVersion resets all changes to the "version" field.
func (m *RequestedLibraryMutation) ResetVersion() {
	m.version = nil
}

// SetStatus sets the "status" field.
func (m *RequestedLibraryMutation) SetStatus(s string) {
	m.status = &s
}

// Status returns the value of the "status" field in the mutation.
func (m *RequestedLibraryMutation) Status() (r string, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the RequestedLibrary entity.
// If the RequestedLibrary object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestedLibraryMutation) OldStatus(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *RequestedLibraryMutation) ResetStatus() {
	m.status = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *RequestedLibraryMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *RequestedLibraryMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the RequestedLibrary entity.
// If the RequestedLibrary object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestedLibraryMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *RequestedLibraryMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *RequestedLibraryMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *RequestedLibraryMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the RequestedLibrary entity.
// If the RequestedLibrary object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestedLibraryMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *RequestedLibraryMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetName sets the "name" field.
func (m *RequestedLibraryMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *RequestedLibraryMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the RequestedLibrary entity.
// If the RequestedLibrary object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestedLibraryMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *RequestedLibraryMutation) ResetName() {
	m.name = nil
}

// SetRequestedBy sets the "requested_by" field.
func (m *RequestedLibraryMutation) SetRequestedBy(s string) {
	m.requested_by = &s
}

// RequestedBy returns the value of the "requested_by" field in the mutation.
func (m *RequestedLibraryMutation) RequestedBy() (r string, exists bool) {
	v := m.requested_by
	if v == nil {
		return
	}
	return *v, true
}

// OldRequestedBy returns the old "requested_by" field's value of the RequestedLibrary entity.
// If the RequestedLibrary object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RequestedLibraryMutation) OldRequestedBy(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRequestedBy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRequestedBy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRequestedBy: %w", err)
	}
	return oldValue.RequestedBy, nil
}

// ResetRequestedBy resets all changes to the "requested_by" field.
func (m *RequestedLibraryMutation) ResetRequestedBy() {
	m.requested_by = nil
}

// Where appends a list predicates to the RequestedLibraryMutation builder.
func (m *RequestedLibraryMutation) Where(ps ...predicate.RequestedLibrary) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the RequestedLibraryMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *RequestedLibraryMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.RequestedLibrary, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *RequestedLibraryMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *RequestedLibraryMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (RequestedLibrary).
func (m *RequestedLibraryMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RequestedLibraryMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.kind != nil {
		fields = append(fields, requestedlibrary.FieldKind)
	}
	if m.version != nil {
		fields = append(fields, requestedlibrary.FieldVersion)
	}
	if m.status != nil {
		fields = append(fields, requestedlibrary.FieldStatus)
	}
	if m.created_at != nil {
		fields = append(fields, requestedlibrary.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, requestedlibrary.FieldUpdatedAt)
	}
	if m.name != nil {
		fields = append(fields, requestedlibrary.FieldName)
	}
	if m.requested_by != nil {
		fields = append(fields, requestedlibrary.FieldRequestedBy)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RequestedLibraryMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case requestedlibrary.FieldKind:
		return m.Kind()
	case requestedlibrary.FieldVersion:
		return m.Version()
	case requestedlibrary.FieldStatus:
		return m.Status()
	case requestedlibrary.FieldCreatedAt:
		return m.CreatedAt()
	case requestedlibrary.FieldUpdatedAt:
		return m.UpdatedAt()
	case requestedlibrary.FieldName:
		return m.Name()
	case requestedlibrary.FieldRequestedBy:
		return m.RequestedBy()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RequestedLibraryMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case requestedlibrary.FieldKind:
		return m.OldKind(ctx)
	case requestedlibrary.FieldVersion:
		return m.OldVersion(ctx)
	case requestedlibrary.FieldStatus:
		return m.OldStatus(ctx)
	case requestedlibrary.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case requestedlibrary.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case requestedlibrary.FieldName:
		return m.OldName(ctx)
	case requestedlibrary.FieldRequestedBy:
		return m.OldRequestedBy(ctx)
	}
	return nil, fmt.Errorf("unknown RequestedLibrary field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RequestedLibraryMutation) SetField(name string, value ent.Value) error {
	switch name {
	case requestedlibrary.FieldKind:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetKind(v)
		return nil
	case requestedlibrary.FieldVersion:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetVersion(v)
		return nil
	case requestedlibrary.FieldStatus:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case requestedlibrary.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case requestedlibrary.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case requestedlibrary.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case requestedlibrary.FieldRequestedBy:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRequestedBy(v)
		return nil
	}
	return fmt.Errorf("unknown RequestedLibrary field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RequestedLibraryMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RequestedLibraryMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RequestedLibraryMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown RequestedLibrary numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RequestedLibraryMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RequestedLibraryMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RequestedLibraryMutation) ClearField(name string) error {
	return fmt.Errorf("unknown RequestedLibrary nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RequestedLibraryMutation) ResetField(name string) error {
	switch name {
	case requestedlibrary.FieldKind:
		m.ResetKind()
		return nil
	case requestedlibrary.FieldVersion:
		m.ResetVersion()
		return nil
	case requestedlibrary.FieldStatus:
		m.ResetStatus()
		return nil
	case requestedlibrary.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case requestedlibrary.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case requestedlibrary.FieldName:
		m.ResetName()
		return nil
	case requestedlibrary.FieldRequestedBy:
		m.ResetRequestedBy()
		return nil
	}
	return fmt.Errorf("unknown RequestedLibrary field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RequestedLibraryMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RequestedLibraryMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RequestedLibraryMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RequestedLibraryMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RequestedLibraryMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RequestedLibraryMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RequestedLibraryMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown RequestedLibrary unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RequestedLibraryMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown RequestedLibrary edge %s", name)
}

// SavedLibraryMutation represents an operation that mutates the SavedLibrary nodes in the graph.
type SavedLibraryMutation struct {
	config
	op            Op
	typ           string
	id            *string
	kind          *string
	version       *string
	status        *string
	created_at    *time.Time
	updated_at    *time.Time
	fullName      *string
	simpleName    *string
	v1            *int
	addv1         *int
	v2            *int
	addv2         *int
	v3            *int
	addv3         *int
	isPublished   *bool
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*SavedLibrary, error)
	predicates    []predicate.SavedLibrary
}

var _ ent.Mutation = (*SavedLibraryMutation)(nil)

// savedlibraryOption allows management of the mutation configuration using functional options.
type savedlibraryOption func(*SavedLibraryMutation)

// newSavedLibraryMutation creates new mutation for the SavedLibrary entity.
func newSavedLibraryMutation(c config, op Op, opts ...savedlibraryOption) *SavedLibraryMutation {
	m := &SavedLibraryMutation{
		config:        c,
		op:            op,
		typ:           TypeSavedLibrary,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSavedLibraryID sets the ID field of the mutation.
func withSavedLibraryID(id string) savedlibraryOption {
	return func(m *SavedLibraryMutation) {
		var (
			err   error
			once  sync.Once
			value *SavedLibrary
		)
		m.oldValue = func(ctx context.Context) (*SavedLibrary, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().SavedLibrary.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSavedLibrary sets the old SavedLibrary of the mutation.
func withSavedLibrary(node *SavedLibrary) savedlibraryOption {
	return func(m *SavedLibraryMutation) {
		m.oldValue = func(context.Context) (*SavedLibrary, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SavedLibraryMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SavedLibraryMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of SavedLibrary entities.
func (m *SavedLibraryMutation) SetID(id string) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SavedLibraryMutation) ID() (id string, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SavedLibraryMutation) IDs(ctx context.Context) ([]string, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []string{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().SavedLibrary.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetKind sets the "kind" field.
func (m *SavedLibraryMutation) SetKind(s string) {
	m.kind = &s
}

// Kind returns the value of the "kind" field in the mutation.
func (m *SavedLibraryMutation) Kind() (r string, exists bool) {
	v := m.kind
	if v == nil {
		return
	}
	return *v, true
}

// OldKind returns the old "kind" field's value of the SavedLibrary entity.
// If the SavedLibrary object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SavedLibraryMutation) OldKind(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldKind is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldKind requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldKind: %w", err)
	}
	return oldValue.Kind, nil
}

// ResetKind resets all changes to the "kind" field.
func (m *SavedLibraryMutation) ResetKind() {
	m.kind = nil
}

// SetVersion sets the "version" field.
func (m *SavedLibraryMutation) SetVersion(s string) {
	m.version = &s
}

// Version returns the value of the "version" field in the mutation.
func (m *SavedLibraryMutation) Version() (r string, exists bool) {
	v := m.version
	if v == nil {
		return
	}
	return *v, true
}

// OldVersion returns the old "version" field's value of the SavedLibrary entity.
// If the SavedLibrary object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SavedLibraryMutation) OldVersion(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldVersion is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldVersion requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldVersion: %w", err)
	}
	return oldValue.Version, nil
}

// ResetVersion resets all changes to the "version" field.
func (m *SavedLibraryMutation) ResetVersion() {
	m.version = nil
}

// SetStatus sets the "status" field.
func (m *SavedLibraryMutation) SetStatus(s string) {
	m.status = &s
}

// Status returns the value of the "status" field in the mutation.
func (m *SavedLibraryMutation) Status() (r string, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the SavedLibrary entity.
// If the SavedLibrary object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SavedLibraryMutation) OldStatus(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *SavedLibraryMutation) ResetStatus() {
	m.status = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *SavedLibraryMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *SavedLibraryMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the SavedLibrary entity.
// If the SavedLibrary object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SavedLibraryMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *SavedLibraryMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *SavedLibraryMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *SavedLibraryMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the SavedLibrary entity.
// If the SavedLibrary object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SavedLibraryMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *SavedLibraryMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetFullName sets the "fullName" field.
func (m *SavedLibraryMutation) SetFullName(s string) {
	m.fullName = &s
}

// FullName returns the value of the "fullName" field in the mutation.
func (m *SavedLibraryMutation) FullName() (r string, exists bool) {
	v := m.fullName
	if v == nil {
		return
	}
	return *v, true
}

// OldFullName returns the old "fullName" field's value of the SavedLibrary entity.
// If the SavedLibrary object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SavedLibraryMutation) OldFullName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldFullName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldFullName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFullName: %w", err)
	}
	return oldValue.FullName, nil
}

// ResetFullName resets all changes to the "fullName" field.
func (m *SavedLibraryMutation) ResetFullName() {
	m.fullName = nil
}

// SetSimpleName sets the "simpleName" field.
func (m *SavedLibraryMutation) SetSimpleName(s string) {
	m.simpleName = &s
}

// SimpleName returns the value of the "simpleName" field in the mutation.
func (m *SavedLibraryMutation) SimpleName() (r string, exists bool) {
	v := m.simpleName
	if v == nil {
		return
	}
	return *v, true
}

// OldSimpleName returns the old "simpleName" field's value of the SavedLibrary entity.
// If the SavedLibrary object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SavedLibraryMutation) OldSimpleName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSimpleName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSimpleName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSimpleName: %w", err)
	}
	return oldValue.SimpleName, nil
}

// ResetSimpleName resets all changes to the "simpleName" field.
func (m *SavedLibraryMutation) ResetSimpleName() {
	m.simpleName = nil
}

// SetV1 sets the "v1" field.
func (m *SavedLibraryMutation) SetV1(i int) {
	m.v1 = &i
	m.addv1 = nil
}

// V1 returns the value of the "v1" field in the mutation.
func (m *SavedLibraryMutation) V1() (r int, exists bool) {
	v := m.v1
	if v == nil {
		return
	}
	return *v, true
}

// OldV1 returns the old "v1" field's value of the SavedLibrary entity.
// If the SavedLibrary object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SavedLibraryMutation) OldV1(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldV1 is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldV1 requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldV1: %w", err)
	}
	return oldValue.V1, nil
}

// AddV1 adds i to the "v1" field.
func (m *SavedLibraryMutation) AddV1(i int) {
	if m.addv1 != nil {
		*m.addv1 += i
	} else {
		m.addv1 = &i
	}
}

// AddedV1 returns the value that was added to the "v1" field in this mutation.
func (m *SavedLibraryMutation) AddedV1() (r int, exists bool) {
	v := m.addv1
	if v == nil {
		return
	}
	return *v, true
}

// ResetV1 resets all changes to the "v1" field.
func (m *SavedLibraryMutation) ResetV1() {
	m.v1 = nil
	m.addv1 = nil
}

// SetV2 sets the "v2" field.
func (m *SavedLibraryMutation) SetV2(i int) {
	m.v2 = &i
	m.addv2 = nil
}

// V2 returns the value of the "v2" field in the mutation.
func (m *SavedLibraryMutation) V2() (r int, exists bool) {
	v := m.v2
	if v == nil {
		return
	}
	return *v, true
}

// OldV2 returns the old "v2" field's value of the SavedLibrary entity.
// If the SavedLibrary object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SavedLibraryMutation) OldV2(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldV2 is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldV2 requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldV2: %w", err)
	}
	return oldValue.V2, nil
}

// AddV2 adds i to the "v2" field.
func (m *SavedLibraryMutation) AddV2(i int) {
	if m.addv2 != nil {
		*m.addv2 += i
	} else {
		m.addv2 = &i
	}
}

// AddedV2 returns the value that was added to the "v2" field in this mutation.
func (m *SavedLibraryMutation) AddedV2() (r int, exists bool) {
	v := m.addv2
	if v == nil {
		return
	}
	return *v, true
}

// ResetV2 resets all changes to the "v2" field.
func (m *SavedLibraryMutation) ResetV2() {
	m.v2 = nil
	m.addv2 = nil
}

// SetV3 sets the "v3" field.
func (m *SavedLibraryMutation) SetV3(i int) {
	m.v3 = &i
	m.addv3 = nil
}

// V3 returns the value of the "v3" field in the mutation.
func (m *SavedLibraryMutation) V3() (r int, exists bool) {
	v := m.v3
	if v == nil {
		return
	}
	return *v, true
}

// OldV3 returns the old "v3" field's value of the SavedLibrary entity.
// If the SavedLibrary object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SavedLibraryMutation) OldV3(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldV3 is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldV3 requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldV3: %w", err)
	}
	return oldValue.V3, nil
}

// AddV3 adds i to the "v3" field.
func (m *SavedLibraryMutation) AddV3(i int) {
	if m.addv3 != nil {
		*m.addv3 += i
	} else {
		m.addv3 = &i
	}
}

// AddedV3 returns the value that was added to the "v3" field in this mutation.
func (m *SavedLibraryMutation) AddedV3() (r int, exists bool) {
	v := m.addv3
	if v == nil {
		return
	}
	return *v, true
}

// ResetV3 resets all changes to the "v3" field.
func (m *SavedLibraryMutation) ResetV3() {
	m.v3 = nil
	m.addv3 = nil
}

// SetIsPublished sets the "isPublished" field.
func (m *SavedLibraryMutation) SetIsPublished(b bool) {
	m.isPublished = &b
}

// IsPublished returns the value of the "isPublished" field in the mutation.
func (m *SavedLibraryMutation) IsPublished() (r bool, exists bool) {
	v := m.isPublished
	if v == nil {
		return
	}
	return *v, true
}

// OldIsPublished returns the old "isPublished" field's value of the SavedLibrary entity.
// If the SavedLibrary object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SavedLibraryMutation) OldIsPublished(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsPublished is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsPublished requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsPublished: %w", err)
	}
	return oldValue.IsPublished, nil
}

// ResetIsPublished resets all changes to the "isPublished" field.
func (m *SavedLibraryMutation) ResetIsPublished() {
	m.isPublished = nil
}

// Where appends a list predicates to the SavedLibraryMutation builder.
func (m *SavedLibraryMutation) Where(ps ...predicate.SavedLibrary) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SavedLibraryMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SavedLibraryMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.SavedLibrary, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SavedLibraryMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SavedLibraryMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (SavedLibrary).
func (m *SavedLibraryMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SavedLibraryMutation) Fields() []string {
	fields := make([]string, 0, 11)
	if m.kind != nil {
		fields = append(fields, savedlibrary.FieldKind)
	}
	if m.version != nil {
		fields = append(fields, savedlibrary.FieldVersion)
	}
	if m.status != nil {
		fields = append(fields, savedlibrary.FieldStatus)
	}
	if m.created_at != nil {
		fields = append(fields, savedlibrary.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, savedlibrary.FieldUpdatedAt)
	}
	if m.fullName != nil {
		fields = append(fields, savedlibrary.FieldFullName)
	}
	if m.simpleName != nil {
		fields = append(fields, savedlibrary.FieldSimpleName)
	}
	if m.v1 != nil {
		fields = append(fields, savedlibrary.FieldV1)
	}
	if m.v2 != nil {
		fields = append(fields, savedlibrary.FieldV2)
	}
	if m.v3 != nil {
		fields = append(fields, savedlibrary.FieldV3)
	}
	if m.isPublished != nil {
		fields = append(fields, savedlibrary.FieldIsPublished)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SavedLibraryMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case savedlibrary.FieldKind:
		return m.Kind()
	case savedlibrary.FieldVersion:
		return m.Version()
	case savedlibrary.FieldStatus:
		return m.Status()
	case savedlibrary.FieldCreatedAt:
		return m.CreatedAt()
	case savedlibrary.FieldUpdatedAt:
		return m.UpdatedAt()
	case savedlibrary.FieldFullName:
		return m.FullName()
	case savedlibrary.FieldSimpleName:
		return m.SimpleName()
	case savedlibrary.FieldV1:
		return m.V1()
	case savedlibrary.FieldV2:
		return m.V2()
	case savedlibrary.FieldV3:
		return m.V3()
	case savedlibrary.FieldIsPublished:
		return m.IsPublished()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SavedLibraryMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case savedlibrary.FieldKind:
		return m.OldKind(ctx)
	case savedlibrary.FieldVersion:
		return m.OldVersion(ctx)
	case savedlibrary.FieldStatus:
		return m.OldStatus(ctx)
	case savedlibrary.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case savedlibrary.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case savedlibrary.FieldFullName:
		return m.OldFullName(ctx)
	case savedlibrary.FieldSimpleName:
		return m.OldSimpleName(ctx)
	case savedlibrary.FieldV1:
		return m.OldV1(ctx)
	case savedlibrary.FieldV2:
		return m.OldV2(ctx)
	case savedlibrary.FieldV3:
		return m.OldV3(ctx)
	case savedlibrary.FieldIsPublished:
		return m.OldIsPublished(ctx)
	}
	return nil, fmt.Errorf("unknown SavedLibrary field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SavedLibraryMutation) SetField(name string, value ent.Value) error {
	switch name {
	case savedlibrary.FieldKind:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetKind(v)
		return nil
	case savedlibrary.FieldVersion:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetVersion(v)
		return nil
	case savedlibrary.FieldStatus:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case savedlibrary.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case savedlibrary.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case savedlibrary.FieldFullName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFullName(v)
		return nil
	case savedlibrary.FieldSimpleName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSimpleName(v)
		return nil
	case savedlibrary.FieldV1:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetV1(v)
		return nil
	case savedlibrary.FieldV2:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetV2(v)
		return nil
	case savedlibrary.FieldV3:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetV3(v)
		return nil
	case savedlibrary.FieldIsPublished:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsPublished(v)
		return nil
	}
	return fmt.Errorf("unknown SavedLibrary field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SavedLibraryMutation) AddedFields() []string {
	var fields []string
	if m.addv1 != nil {
		fields = append(fields, savedlibrary.FieldV1)
	}
	if m.addv2 != nil {
		fields = append(fields, savedlibrary.FieldV2)
	}
	if m.addv3 != nil {
		fields = append(fields, savedlibrary.FieldV3)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SavedLibraryMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case savedlibrary.FieldV1:
		return m.AddedV1()
	case savedlibrary.FieldV2:
		return m.AddedV2()
	case savedlibrary.FieldV3:
		return m.AddedV3()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SavedLibraryMutation) AddField(name string, value ent.Value) error {
	switch name {
	case savedlibrary.FieldV1:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddV1(v)
		return nil
	case savedlibrary.FieldV2:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddV2(v)
		return nil
	case savedlibrary.FieldV3:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddV3(v)
		return nil
	}
	return fmt.Errorf("unknown SavedLibrary numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SavedLibraryMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SavedLibraryMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SavedLibraryMutation) ClearField(name string) error {
	return fmt.Errorf("unknown SavedLibrary nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SavedLibraryMutation) ResetField(name string) error {
	switch name {
	case savedlibrary.FieldKind:
		m.ResetKind()
		return nil
	case savedlibrary.FieldVersion:
		m.ResetVersion()
		return nil
	case savedlibrary.FieldStatus:
		m.ResetStatus()
		return nil
	case savedlibrary.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case savedlibrary.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case savedlibrary.FieldFullName:
		m.ResetFullName()
		return nil
	case savedlibrary.FieldSimpleName:
		m.ResetSimpleName()
		return nil
	case savedlibrary.FieldV1:
		m.ResetV1()
		return nil
	case savedlibrary.FieldV2:
		m.ResetV2()
		return nil
	case savedlibrary.FieldV3:
		m.ResetV3()
		return nil
	case savedlibrary.FieldIsPublished:
		m.ResetIsPublished()
		return nil
	}
	return fmt.Errorf("unknown SavedLibrary field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SavedLibraryMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SavedLibraryMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SavedLibraryMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SavedLibraryMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SavedLibraryMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SavedLibraryMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SavedLibraryMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown SavedLibrary unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SavedLibraryMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown SavedLibrary edge %s", name)
}
