// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"web_app/ent/requestedlibrary"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RequestedLibraryCreate is the builder for creating a RequestedLibrary entity.
type RequestedLibraryCreate struct {
	config
	mutation *RequestedLibraryMutation
	hooks    []Hook
}

// SetKind sets the "kind" field.
func (_c *RequestedLibraryCreate) SetKind(v string) *RequestedLibraryCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *RequestedLibraryCreate) SetVersion(v string) *RequestedLibraryCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *RequestedLibraryCreate) SetStatus(v string) *RequestedLibraryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RequestedLibraryCreate) SetNillableStatus(v *string) *RequestedLibraryCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RequestedLibraryCreate) SetCreatedAt(v time.Time) *RequestedLibraryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RequestedLibraryCreate) SetNillableCreatedAt(v *time.Time) *RequestedLibraryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RequestedLibraryCreate) SetUpdatedAt(v time.Time) *RequestedLibraryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RequestedLibraryCreate) SetNillableUpdatedAt(v *time.Time) *RequestedLibraryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *RequestedLibraryCreate) SetName(v string) *RequestedLibraryCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetRequestedBy sets the "requested_by" field.
func (_c *RequestedLibraryCreate) SetRequestedBy(v string) *RequestedLibraryCreate {
	_c.mutation.SetRequestedBy(v)
	return _c
}

// SetID sets the "id" field.
func (_c *RequestedLibraryCreate) SetID(v string) *RequestedLibraryCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the RequestedLibraryMutation object of the builder.
func (_c *RequestedLibraryCreate) Mutation() *RequestedLibraryMutation {
	return _c.mutation
}

// Save creates the RequestedLibrary in the database.
func (_c *RequestedLibraryCreate) Save(ctx context.Context) (*RequestedLibrary, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RequestedLibraryCreate) SaveX(ctx context.Context) *RequestedLibrary {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestedLibraryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestedLibraryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RequestedLibraryCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := requestedlibrary.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := requestedlibrary.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := requestedlibrary.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RequestedLibraryCreate) check() error {
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "RequestedLibrary.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := requestedlibrary.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "RequestedLibrary.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "RequestedLibrary.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := requestedlibrary.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "RequestedLibrary.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RequestedLibrary.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := requestedlibrary.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RequestedLibrary.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RequestedLibrary.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RequestedLibrary.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RequestedLibrary.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := requestedlibrary.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RequestedLibrary.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestedBy(); !ok {
		return &ValidationError{Name: "requested_by", err: errors.New(`ent: missing required field "RequestedLibrary.requested_by"`)}
	}
	if v, ok := _c.mutation.RequestedBy(); ok {
		if err := requestedlibrary.RequestedByValidator(v); err != nil {
			return &ValidationError{Name: "requested_by", err: fmt.Errorf(`ent: validator failed for field "RequestedLibrary.requested_by": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := requestedlibrary.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "RequestedLibrary.id": %w`, err)}
		}
	}
	return nil
}

func (_c *RequestedLibraryCreate) sqlSave(ctx context.Context) (*RequestedLibrary, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected RequestedLibrary.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RequestedLibraryCreate) createSpec() (*RequestedLibrary, *sqlgraph.CreateSpec) {
	var (
		_node = &RequestedLibrary{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(requestedlibrary.Table, sqlgraph.NewFieldSpec(requestedlibrary.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(requestedlibrary.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(requestedlibrary.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(requestedlibrary.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(requestedlibrary.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(requestedlibrary.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(requestedlibrary.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.RequestedBy(); ok {
		_spec.SetField(requestedlibrary.FieldRequestedBy, field.TypeString, value)
		_node.RequestedBy = value
	}
	return _node, _spec
}

// RequestedLibraryCreateBulk is the builder for creating many RequestedLibrary entities in bulk.
type RequestedLibraryCreateBulk struct {
	config
	err      error
	builders []*RequestedLibraryCreate
}

// Save creates the RequestedLibrary entities in the database.
func (_c *RequestedLibraryCreateBulk) Save(ctx context.Context) ([]*RequestedLibrary, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RequestedLibrary, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestedLibraryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RequestedLibraryCreateBulk) SaveX(ctx context.Context) []*RequestedLibrary {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestedLibraryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestedLibraryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
