// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"web_app/ent/predicate"
	"web_app/ent/requestedlibrary"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RequestedLibraryUpdate is the builder for updating RequestedLibrary entities.
type RequestedLibraryUpdate struct {
	config
	hooks    []Hook
	mutation *RequestedLibraryMutation
}

// Where appends a list predicates to the RequestedLibraryUpdate builder.
func (_u *RequestedLibraryUpdate) Where(ps ...predicate.RequestedLibrary) *RequestedLibraryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *RequestedLibraryUpdate) SetName(v string) *RequestedLibraryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RequestedLibraryUpdate) SetNillableName(v *string) *RequestedLibraryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetV1 sets the "v1" field.
func (_u *RequestedLibraryUpdate) SetV1(v int) *RequestedLibraryUpdate {
	_u.mutation.ResetV1()
	_u.mutation.SetV1(v)
	return _u
}

// SetNillableV1 sets the "v1" field if the given value is not nil.
func (_u *RequestedLibraryUpdate) SetNillableV1(v *int) *RequestedLibraryUpdate {
	if v != nil {
		_u.SetV1(*v)
	}
	return _u
}

// AddV1 adds value to the "v1" field.
func (_u *RequestedLibraryUpdate) AddV1(v int) *RequestedLibraryUpdate {
	_u.mutation.AddV1(v)
	return _u
}

// SetV2 sets the "v2" field.
func (_u *RequestedLibraryUpdate) SetV2(v int) *RequestedLibraryUpdate {
	_u.mutation.ResetV2()
	_u.mutation.SetV2(v)
	return _u
}

// SetNillableV2 sets the "v2" field if the given value is not nil.
func (_u *RequestedLibraryUpdate) SetNillableV2(v *int) *RequestedLibraryUpdate {
	if v != nil {
		_u.SetV2(*v)
	}
	return _u
}

// AddV2 adds value to the "v2" field.
func (_u *RequestedLibraryUpdate) AddV2(v int) *RequestedLibraryUpdate {
	_u.mutation.AddV2(v)
	return _u
}

// SetV3 sets the "v3" field.
func (_u *RequestedLibraryUpdate) SetV3(v int) *RequestedLibraryUpdate {
	_u.mutation.ResetV3()
	_u.mutation.SetV3(v)
	return _u
}

// SetNillableV3 sets the "v3" field if the given value is not nil.
func (_u *RequestedLibraryUpdate) SetNillableV3(v *int) *RequestedLibraryUpdate {
	if v != nil {
		_u.SetV3(*v)
	}
	return _u
}

// AddV3 adds value to the "v3" field.
func (_u *RequestedLibraryUpdate) AddV3(v int) *RequestedLibraryUpdate {
	_u.mutation.AddV3(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *RequestedLibraryUpdate) SetStatus(v string) *RequestedLibraryUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RequestedLibraryUpdate) SetNillableStatus(v *string) *RequestedLibraryUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RequestedLibraryUpdate) SetUpdatedAt(v time.Time) *RequestedLibraryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *RequestedLibraryUpdate) SetVersion(v string) *RequestedLibraryUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *RequestedLibraryUpdate) SetNillableVersion(v *string) *RequestedLibraryUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetRequestedBy sets the "requested_by" field.
func (_u *RequestedLibraryUpdate) SetRequestedBy(v string) *RequestedLibraryUpdate {
	_u.mutation.SetRequestedBy(v)
	return _u
}

// SetNillableRequestedBy sets the "requested_by" field if the given value is not nil.
func (_u *RequestedLibraryUpdate) SetNillableRequestedBy(v *string) *RequestedLibraryUpdate {
	if v != nil {
		_u.SetRequestedBy(*v)
	}
	return _u
}

// Mutation returns the RequestedLibraryMutation object of the builder.
func (_u *RequestedLibraryUpdate) Mutation() *RequestedLibraryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RequestedLibraryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestedLibraryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RequestedLibraryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestedLibraryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RequestedLibraryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := requestedlibrary.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestedLibraryUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := requestedlibrary.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RequestedLibrary.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.V1(); ok {
		if err := requestedlibrary.V1Validator(v); err != nil {
			return &ValidationError{Name: "v1", err: fmt.Errorf(`ent: validator failed for field "RequestedLibrary.v1": %w`, err)}
		}
	}
	if v, ok := _u.mutation.V2(); ok {
		if err := requestedlibrary.V2Validator(v); err != nil {
			return &ValidationError{Name: "v2", err: fmt.Errorf(`ent: validator failed for field "RequestedLibrary.v2": %w`, err)}
		}
	}
	if v, ok := _u.mutation.V3(); ok {
		if err := requestedlibrary.V3Validator(v); err != nil {
			return &ValidationError{Name: "v3", err: fmt.Errorf(`ent: validator failed for field "RequestedLibrary.v3": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := requestedlibrary.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RequestedLibrary.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestedBy(); ok {
		if err := requestedlibrary.RequestedByValidator(v); err != nil {
			return &ValidationError{Name: "requested_by", err: fmt.Errorf(`ent: validator failed for field "RequestedLibrary.requested_by": %w`, err)}
		}
	}
	return nil
}

func (_u *RequestedLibraryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestedlibrary.Table, requestedlibrary.Columns, sqlgraph.NewFieldSpec(requestedlibrary.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(requestedlibrary.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.V1(); ok {
		_spec.SetField(requestedlibrary.FieldV1, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedV1(); ok {
		_spec.AddField(requestedlibrary.FieldV1, field.TypeInt, value)
	}
	if value, ok := _u.mutation.V2(); ok {
		_spec.SetField(requestedlibrary.FieldV2, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedV2(); ok {
		_spec.AddField(requestedlibrary.FieldV2, field.TypeInt, value)
	}
	if value, ok := _u.mutation.V3(); ok {
		_spec.SetField(requestedlibrary.FieldV3, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedV3(); ok {
		_spec.AddField(requestedlibrary.FieldV3, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(requestedlibrary.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(requestedlibrary.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(requestedlibrary.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestedBy(); ok {
		_spec.SetField(requestedlibrary.FieldRequestedBy, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestedlibrary.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RequestedLibraryUpdateOne is the builder for updating a single RequestedLibrary entity.
type RequestedLibraryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RequestedLibraryMutation
}

// SetName sets the "name" field.
func (_u *RequestedLibraryUpdateOne) SetName(v string) *RequestedLibraryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RequestedLibraryUpdateOne) SetNillableName(v *string) *RequestedLibraryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetV1 sets the "v1" field.
func (_u *RequestedLibraryUpdateOne) SetV1(v int) *RequestedLibraryUpdateOne {
	_u.mutation.ResetV1()
	_u.mutation.SetV1(v)
	return _u
}

// SetNillableV1 sets the "v1" field if the given value is not nil.
func (_u *RequestedLibraryUpdateOne) SetNillableV1(v *int) *RequestedLibraryUpdateOne {
	if v != nil {
		_u.SetV1(*v)
	}
	return _u
}

// AddV1 adds value to the "v1" field.
func (_u *RequestedLibraryUpdateOne) AddV1(v int) *RequestedLibraryUpdateOne {
	_u.mutation.AddV1(v)
	return _u
}

// SetV2 sets the "v2" field.
func (_u *RequestedLibraryUpdateOne) SetV2(v int) *RequestedLibraryUpdateOne {
	_u.mutation.ResetV2()
	_u.mutation.SetV2(v)
	return _u
}

// SetNillableV2 sets the "v2" field if the given value is not nil.
func (_u *RequestedLibraryUpdateOne) SetNillableV2(v *int) *RequestedLibraryUpdateOne {
	if v != nil {
		_u.SetV2(*v)
	}
	return _u
}

// AddV2 adds value to the "v2" field.
func (_u *RequestedLibraryUpdateOne) AddV2(v int) *RequestedLibraryUpdateOne {
	_u.mutation.AddV2(v)
	return _u
}

// SetV3 sets the "v3" field.
func (_u *RequestedLibraryUpdateOne) SetV3(v int) *RequestedLibraryUpdateOne {
	_u.mutation.ResetV3()
	_u.mutation.SetV3(v)
	return _u
}

// SetNillableV3 sets the "v3" field if the given value is not nil.
func (_u *RequestedLibraryUpdateOne) SetNillableV3(v *int) *RequestedLibraryUpdateOne {
	if v != nil {
		_u.SetV3(*v)
	}
	return _u
}

// AddV3 adds value to the "v3" field.
func (_u *RequestedLibraryUpdateOne) AddV3(v int) *RequestedLibraryUpdateOne {
	_u.mutation.AddV3(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *RequestedLibraryUpdateOne) SetStatus(v string) *RequestedLibraryUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RequestedLibraryUpdateOne) SetNillableStatus(v *string) *RequestedLibraryUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RequestedLibraryUpdateOne) SetUpdatedAt(v time.Time) *RequestedLibraryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetVersion sets the "version" field.
func (_u *RequestedLibraryUpdateOne) SetVersion(v string) *RequestedLibraryUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *RequestedLibraryUpdateOne) SetNillableVersion(v *string) *RequestedLibraryUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetRequestedBy sets the "requested_by" field.
func (_u *RequestedLibraryUpdateOne) SetRequestedBy(v string) *RequestedLibraryUpdateOne {
	_u.mutation.SetRequestedBy(v)
	return _u
}

// SetNillableRequestedBy sets the "requested_by" field if the given value is not nil.
func (_u *RequestedLibraryUpdateOne) SetNillableRequestedBy(v *string) *RequestedLibraryUpdateOne {
	if v != nil {
		_u.SetRequestedBy(*v)
	}
	return _u
}

// Mutation returns the RequestedLibraryMutation object of the builder.
func (_u *RequestedLibraryUpdateOne) Mutation() *RequestedLibraryMutation {
	return _u.mutation
}

// Where appends a list predicates to the RequestedLibraryUpdate builder.
func (_u *RequestedLibraryUpdateOne) Where(ps ...predicate.RequestedLibrary) *RequestedLibraryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RequestedLibraryUpdateOne) Select(field string, fields ...string) *RequestedLibraryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RequestedLibrary entity.
func (_u *RequestedLibraryUpdateOne) Save(ctx context.Context) (*RequestedLibrary, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestedLibraryUpdateOne) SaveX(ctx context.Context) *RequestedLibrary {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RequestedLibraryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestedLibraryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RequestedLibraryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := requestedlibrary.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestedLibraryUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := requestedlibrary.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RequestedLibrary.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.V1(); ok {
		if err := requestedlibrary.V1Validator(v); err != nil {
			return &ValidationError{Name: "v1", err: fmt.Errorf(`ent: validator failed for field "RequestedLibrary.v1": %w`, err)}
		}
	}
	if v, ok := _u.mutation.V2(); ok {
		if err := requestedlibrary.V2Validator(v); err != nil {
			return &ValidationError{Name: "v2", err: fmt.Errorf(`ent: validator failed for field "RequestedLibrary.v2": %w`, err)}
		}
	}
	if v, ok := _u.mutation.V3(); ok {
		if err := requestedlibrary.V3Validator(v); err != nil {
			return &ValidationError{Name: "v3", err: fmt.Errorf(`ent: validator failed for field "RequestedLibrary.v3": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := requestedlibrary.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RequestedLibrary.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestedBy(); ok {
		if err := requestedlibrary.RequestedByValidator(v); err != nil {
			return &ValidationError{Name: "requested_by", err: fmt.Errorf(`ent: validator failed for field "RequestedLibrary.requested_by": %w`, err)}
		}
	}
	return nil
}

func (_u *RequestedLibraryUpdateOne) sqlSave(ctx context.Context) (_node *RequestedLibrary, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestedlibrary.Table, requestedlibrary.Columns, sqlgraph.NewFieldSpec(requestedlibrary.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RequestedLibrary.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requestedlibrary.FieldID)
		for _, f := range fields {
			if !requestedlibrary.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != requestedlibrary.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(requestedlibrary.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.V1(); ok {
		_spec.SetField(requestedlibrary.FieldV1, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedV1(); ok {
		_spec.AddField(requestedlibrary.FieldV1, field.TypeInt, value)
	}
	if value, ok := _u.mutation.V2(); ok {
		_spec.SetField(requestedlibrary.FieldV2, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedV2(); ok {
		_spec.AddField(requestedlibrary.FieldV2, field.TypeInt, value)
	}
	if value, ok := _u.mutation.V3(); ok {
		_spec.SetField(requestedlibrary.FieldV3, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedV3(); ok {
		_spec.AddField(requestedlibrary.FieldV3, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(requestedlibrary.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(requestedlibrary.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(requestedlibrary.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestedBy(); ok {
		_spec.SetField(requestedlibrary.FieldRequestedBy, field.TypeString, value)
	}
	_node = &RequestedLibrary{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestedlibrary.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
