// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"web_app/ent/savedlibrary"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SavedLibrary is the model entity for the SavedLibrary schema.
type SavedLibrary struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// V1 holds the value of the "v1" field.
	V1 int `json:"v1,omitempty"`
	// V2 holds the value of the "v2" field.
	V2 int `json:"v2,omitempty"`
	// V3 holds the value of the "v3" field.
	V3 int `json:"v3,omitempty"`
	// IsPublished holds the value of the "isPublished" field.
	IsPublished  bool `json:"isPublished,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SavedLibrary) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case savedlibrary.FieldIsPublished:
			values[i] = new(sql.NullBool)
		case savedlibrary.FieldV1, savedlibrary.FieldV2, savedlibrary.FieldV3:
			values[i] = new(sql.NullInt64)
		case savedlibrary.FieldID, savedlibrary.FieldKind, savedlibrary.FieldName, savedlibrary.FieldVersion, savedlibrary.FieldStatus:
			values[i] = new(sql.NullString)
		case savedlibrary.FieldCreatedAt, savedlibrary.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SavedLibrary fields.
func (_m *SavedLibrary) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case savedlibrary.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case savedlibrary.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case savedlibrary.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case savedlibrary.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case savedlibrary.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case savedlibrary.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case savedlibrary.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case savedlibrary.FieldV1:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field v1", values[i])
			} else if value.Valid {
				_m.V1 = int(value.Int64)
			}
		case savedlibrary.FieldV2:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field v2", values[i])
			} else if value.Valid {
				_m.V2 = int(value.Int64)
			}
		case savedlibrary.FieldV3:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field v3", values[i])
			} else if value.Valid {
				_m.V3 = int(value.Int64)
			}
		case savedlibrary.FieldIsPublished:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field isPublished", values[i])
			} else if value.Valid {
				_m.IsPublished = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SavedLibrary.
// This includes values selected through modifiers, order, etc.
func (_m *SavedLibrary) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SavedLibrary.
// Note that you need to call SavedLibrary.Unwrap() before calling this method if this SavedLibrary
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SavedLibrary) Update() *SavedLibraryUpdateOne {
	return NewSavedLibraryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SavedLibrary entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SavedLibrary) Unwrap() *SavedLibrary {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SavedLibrary is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SavedLibrary) String() string {
	var builder strings.Builder
	builder.WriteString("SavedLibrary(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("v1=")
	builder.WriteString(fmt.Sprintf("%v", _m.V1))
	builder.WriteString(", ")
	builder.WriteString("v2=")
	builder.WriteString(fmt.Sprintf("%v", _m.V2))
	builder.WriteString(", ")
	builder.WriteString("v3=")
	builder.WriteString(fmt.Sprintf("%v", _m.V3))
	builder.WriteString(", ")
	builder.WriteString("isPublished=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsPublished))
	builder.WriteByte(')')
	return builder.String()
}

// SavedLibraries is a parsable slice of SavedLibrary.
type SavedLibraries []*SavedLibrary
