// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"web_app/ent/predicate"
	"web_app/ent/savedlibrary"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SavedLibraryDelete is the builder for deleting a SavedLibrary entity.
type SavedLibraryDelete struct {
	config
	hooks    []Hook
	mutation *SavedLibraryMutation
}

// Where appends a list predicates to the SavedLibraryDelete builder.
func (_d *SavedLibraryDelete) Where(ps ...predicate.SavedLibrary) *SavedLibraryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SavedLibraryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SavedLibraryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SavedLibraryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(savedlibrary.Table, sqlgraph.NewFieldSpec(savedlibrary.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SavedLibraryDeleteOne is the builder for deleting a single SavedLibrary entity.
type SavedLibraryDeleteOne struct {
	_d *SavedLibraryDelete
}

// Where appends a list predicates to the SavedLibraryDelete builder.
func (_d *SavedLibraryDeleteOne) Where(ps ...predicate.SavedLibrary) *SavedLibraryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SavedLibraryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{savedlibrary.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SavedLibraryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
