// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"web_app/ent/savedlibrary"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SavedLibraryCreate is the builder for creating a SavedLibrary entity.
type SavedLibraryCreate struct {
	config
	mutation *SavedLibraryMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *SavedLibraryCreate) SetName(v string) *SavedLibraryCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *SavedLibraryCreate) SetVersion(v string) *SavedLibraryCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *SavedLibraryCreate) SetStatus(v string) *SavedLibraryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SavedLibraryCreate) SetNillableStatus(v *string) *SavedLibraryCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SavedLibraryCreate) SetCreatedAt(v time.Time) *SavedLibraryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SavedLibraryCreate) SetNillableCreatedAt(v *time.Time) *SavedLibraryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SavedLibraryCreate) SetUpdatedAt(v time.Time) *SavedLibraryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SavedLibraryCreate) SetNillableUpdatedAt(v *time.Time) *SavedLibraryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetV1 sets the "v1" field.
func (_c *SavedLibraryCreate) SetV1(v int) *SavedLibraryCreate {
	_c.mutation.SetV1(v)
	return _c
}

// SetV2 sets the "v2" field.
func (_c *SavedLibraryCreate) SetV2(v int) *SavedLibraryCreate {
	_c.mutation.SetV2(v)
	return _c
}

// SetV3 sets the "v3" field.
func (_c *SavedLibraryCreate) SetV3(v int) *SavedLibraryCreate {
	_c.mutation.SetV3(v)
	return _c
}

// SetIsPublished sets the "isPublished" field.
func (_c *SavedLibraryCreate) SetIsPublished(v bool) *SavedLibraryCreate {
	_c.mutation.SetIsPublished(v)
	return _c
}

// SetNillableIsPublished sets the "isPublished" field if the given value is not nil.
func (_c *SavedLibraryCreate) SetNillableIsPublished(v *bool) *SavedLibraryCreate {
	if v != nil {
		_c.SetIsPublished(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SavedLibraryCreate) SetID(v string) *SavedLibraryCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the SavedLibraryMutation object of the builder.
func (_c *SavedLibraryCreate) Mutation() *SavedLibraryMutation {
	return _c.mutation
}

// Save creates the SavedLibrary in the database.
func (_c *SavedLibraryCreate) Save(ctx context.Context) (*SavedLibrary, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SavedLibraryCreate) SaveX(ctx context.Context) *SavedLibrary {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SavedLibraryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SavedLibraryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SavedLibraryCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := savedlibrary.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := savedlibrary.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := savedlibrary.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IsPublished(); !ok {
		v := savedlibrary.DefaultIsPublished
		_c.mutation.SetIsPublished(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SavedLibraryCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SavedLibrary.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := savedlibrary.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SavedLibrary.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "SavedLibrary.version"`)}
	}
	if v, ok := _c.mutation.Version(); ok {
		if err := savedlibrary.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "SavedLibrary.version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SavedLibrary.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := savedlibrary.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SavedLibrary.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SavedLibrary.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SavedLibrary.updated_at"`)}
	}
	if _, ok := _c.mutation.V1(); !ok {
		return &ValidationError{Name: "v1", err: errors.New(`ent: missing required field "SavedLibrary.v1"`)}
	}
	if v, ok := _c.mutation.V1(); ok {
		if err := savedlibrary.V1Validator(v); err != nil {
			return &ValidationError{Name: "v1", err: fmt.Errorf(`ent: validator failed for field "SavedLibrary.v1": %w`, err)}
		}
	}
	if _, ok := _c.mutation.V2(); !ok {
		return &ValidationError{Name: "v2", err: errors.New(`ent: missing required field "SavedLibrary.v2"`)}
	}
	if v, ok := _c.mutation.V2(); ok {
		if err := savedlibrary.V2Validator(v); err != nil {
			return &ValidationError{Name: "v2", err: fmt.Errorf(`ent: validator failed for field "SavedLibrary.v2": %w`, err)}
		}
	}
	if _, ok := _c.mutation.V3(); !ok {
		return &ValidationError{Name: "v3", err: errors.New(`ent: missing required field "SavedLibrary.v3"`)}
	}
	if v, ok := _c.mutation.V3(); ok {
		if err := savedlibrary.V3Validator(v); err != nil {
			return &ValidationError{Name: "v3", err: fmt.Errorf(`ent: validator failed for field "SavedLibrary.v3": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsPublished(); !ok {
		return &ValidationError{Name: "isPublished", err: errors.New(`ent: missing required field "SavedLibrary.isPublished"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := savedlibrary.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SavedLibrary.id": %w`, err)}
		}
	}
	return nil
}

func (_c *SavedLibraryCreate) sqlSave(ctx context.Context) (*SavedLibrary, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SavedLibrary.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SavedLibraryCreate) createSpec() (*SavedLibrary, *sqlgraph.CreateSpec) {
	var (
		_node = &SavedLibrary{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(savedlibrary.Table, sqlgraph.NewFieldSpec(savedlibrary.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(savedlibrary.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(savedlibrary.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(savedlibrary.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(savedlibrary.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(savedlibrary.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.V1(); ok {
		_spec.SetField(savedlibrary.FieldV1, field.TypeInt, value)
		_node.V1 = value
	}
	if value, ok := _c.mutation.V2(); ok {
		_spec.SetField(savedlibrary.FieldV2, field.TypeInt, value)
		_node.V2 = value
	}
	if value, ok := _c.mutation.V3(); ok {
		_spec.SetField(savedlibrary.FieldV3, field.TypeInt, value)
		_node.V3 = value
	}
	if value, ok := _c.mutation.IsPublished(); ok {
		_spec.SetField(savedlibrary.FieldIsPublished, field.TypeBool, value)
		_node.IsPublished = value
	}
	return _node, _spec
}

// SavedLibraryCreateBulk is the builder for creating many SavedLibrary entities in bulk.
type SavedLibraryCreateBulk struct {
	config
	err      error
	builders []*SavedLibraryCreate
}

// Save creates the SavedLibrary entities in the database.
func (_c *SavedLibraryCreateBulk) Save(ctx context.Context) ([]*SavedLibrary, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SavedLibrary, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SavedLibraryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SavedLibraryCreateBulk) SaveX(ctx context.Context) []*SavedLibrary {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SavedLibraryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SavedLibraryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
