// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"web_app/ent/predicate"
	"web_app/ent/savedlibrary"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SavedLibraryUpdate is the builder for updating SavedLibrary entities.
type SavedLibraryUpdate struct {
	config
	hooks    []Hook
	mutation *SavedLibraryMutation
}

// Where appends a list predicates to the SavedLibraryUpdate builder.
func (_u *SavedLibraryUpdate) Where(ps ...predicate.SavedLibrary) *SavedLibraryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKind sets the "kind" field.
func (_u *SavedLibraryUpdate) SetKind(v string) *SavedLibraryUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *SavedLibraryUpdate) SetNillableKind(v *string) *SavedLibraryUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SavedLibraryUpdate) SetName(v string) *SavedLibraryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SavedLibraryUpdate) SetNillableName(v *string) *SavedLibraryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *SavedLibraryUpdate) SetVersion(v string) *SavedLibraryUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *SavedLibraryUpdate) SetNillableVersion(v *string) *SavedLibraryUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SavedLibraryUpdate) SetStatus(v string) *SavedLibraryUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SavedLibraryUpdate) SetNillableStatus(v *string) *SavedLibraryUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SavedLibraryUpdate) SetUpdatedAt(v time.Time) *SavedLibraryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetV1 sets the "v1" field.
func (_u *SavedLibraryUpdate) SetV1(v int) *SavedLibraryUpdate {
	_u.mutation.ResetV1()
	_u.mutation.SetV1(v)
	return _u
}

// SetNillableV1 sets the "v1" field if the given value is not nil.
func (_u *SavedLibraryUpdate) SetNillableV1(v *int) *SavedLibraryUpdate {
	if v != nil {
		_u.SetV1(*v)
	}
	return _u
}

// AddV1 adds value to the "v1" field.
func (_u *SavedLibraryUpdate) AddV1(v int) *SavedLibraryUpdate {
	_u.mutation.AddV1(v)
	return _u
}

// SetV2 sets the "v2" field.
func (_u *SavedLibraryUpdate) SetV2(v int) *SavedLibraryUpdate {
	_u.mutation.ResetV2()
	_u.mutation.SetV2(v)
	return _u
}

// SetNillableV2 sets the "v2" field if the given value is not nil.
func (_u *SavedLibraryUpdate) SetNillableV2(v *int) *SavedLibraryUpdate {
	if v != nil {
		_u.SetV2(*v)
	}
	return _u
}

// AddV2 adds value to the "v2" field.
func (_u *SavedLibraryUpdate) AddV2(v int) *SavedLibraryUpdate {
	_u.mutation.AddV2(v)
	return _u
}

// SetV3 sets the "v3" field.
func (_u *SavedLibraryUpdate) SetV3(v int) *SavedLibraryUpdate {
	_u.mutation.ResetV3()
	_u.mutation.SetV3(v)
	return _u
}

// SetNillableV3 sets the "v3" field if the given value is not nil.
func (_u *SavedLibraryUpdate) SetNillableV3(v *int) *SavedLibraryUpdate {
	if v != nil {
		_u.SetV3(*v)
	}
	return _u
}

// AddV3 adds value to the "v3" field.
func (_u *SavedLibraryUpdate) AddV3(v int) *SavedLibraryUpdate {
	_u.mutation.AddV3(v)
	return _u
}

// SetIsPublished sets the "isPublished" field.
func (_u *SavedLibraryUpdate) SetIsPublished(v bool) *SavedLibraryUpdate {
	_u.mutation.SetIsPublished(v)
	return _u
}

// SetNillableIsPublished sets the "isPublished" field if the given value is not nil.
func (_u *SavedLibraryUpdate) SetNillableIsPublished(v *bool) *SavedLibraryUpdate {
	if v != nil {
		_u.SetIsPublished(*v)
	}
	return _u
}

// Mutation returns the SavedLibraryMutation object of the builder.
func (_u *SavedLibraryUpdate) Mutation() *SavedLibraryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SavedLibraryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SavedLibraryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SavedLibraryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SavedLibraryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SavedLibraryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := savedlibrary.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SavedLibraryUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := savedlibrary.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "SavedLibrary.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := savedlibrary.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SavedLibrary.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := savedlibrary.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "SavedLibrary.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := savedlibrary.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SavedLibrary.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.V1(); ok {
		if err := savedlibrary.V1Validator(v); err != nil {
			return &ValidationError{Name: "v1", err: fmt.Errorf(`ent: validator failed for field "SavedLibrary.v1": %w`, err)}
		}
	}
	if v, ok := _u.mutation.V2(); ok {
		if err := savedlibrary.V2Validator(v); err != nil {
			return &ValidationError{Name: "v2", err: fmt.Errorf(`ent: validator failed for field "SavedLibrary.v2": %w`, err)}
		}
	}
	if v, ok := _u.mutation.V3(); ok {
		if err := savedlibrary.V3Validator(v); err != nil {
			return &ValidationError{Name: "v3", err: fmt.Errorf(`ent: validator failed for field "SavedLibrary.v3": %w`, err)}
		}
	}
	return nil
}

func (_u *SavedLibraryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(savedlibrary.Table, savedlibrary.Columns, sqlgraph.NewFieldSpec(savedlibrary.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(savedlibrary.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(savedlibrary.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(savedlibrary.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(savedlibrary.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(savedlibrary.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.V1(); ok {
		_spec.SetField(savedlibrary.FieldV1, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedV1(); ok {
		_spec.AddField(savedlibrary.FieldV1, field.TypeInt, value)
	}
	if value, ok := _u.mutation.V2(); ok {
		_spec.SetField(savedlibrary.FieldV2, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedV2(); ok {
		_spec.AddField(savedlibrary.FieldV2, field.TypeInt, value)
	}
	if value, ok := _u.mutation.V3(); ok {
		_spec.SetField(savedlibrary.FieldV3, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedV3(); ok {
		_spec.AddField(savedlibrary.FieldV3, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsPublished(); ok {
		_spec.SetField(savedlibrary.FieldIsPublished, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{savedlibrary.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SavedLibraryUpdateOne is the builder for updating a single SavedLibrary entity.
type SavedLibraryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SavedLibraryMutation
}

// SetKind sets the "kind" field.
func (_u *SavedLibraryUpdateOne) SetKind(v string) *SavedLibraryUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *SavedLibraryUpdateOne) SetNillableKind(v *string) *SavedLibraryUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *SavedLibraryUpdateOne) SetName(v string) *SavedLibraryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SavedLibraryUpdateOne) SetNillableName(v *string) *SavedLibraryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *SavedLibraryUpdateOne) SetVersion(v string) *SavedLibraryUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *SavedLibraryUpdateOne) SetNillableVersion(v *string) *SavedLibraryUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SavedLibraryUpdateOne) SetStatus(v string) *SavedLibraryUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SavedLibraryUpdateOne) SetNillableStatus(v *string) *SavedLibraryUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SavedLibraryUpdateOne) SetUpdatedAt(v time.Time) *SavedLibraryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetV1 sets the "v1" field.
func (_u *SavedLibraryUpdateOne) SetV1(v int) *SavedLibraryUpdateOne {
	_u.mutation.ResetV1()
	_u.mutation.SetV1(v)
	return _u
}

// SetNillableV1 sets the "v1" field if the given value is not nil.
func (_u *SavedLibraryUpdateOne) SetNillableV1(v *int) *SavedLibraryUpdateOne {
	if v != nil {
		_u.SetV1(*v)
	}
	return _u
}

// AddV1 adds value to the "v1" field.
func (_u *SavedLibraryUpdateOne) AddV1(v int) *SavedLibraryUpdateOne {
	_u.mutation.AddV1(v)
	return _u
}

// SetV2 sets the "v2" field.
func (_u *SavedLibraryUpdateOne) SetV2(v int) *SavedLibraryUpdateOne {
	_u.mutation.ResetV2()
	_u.mutation.SetV2(v)
	return _u
}

// SetNillableV2 sets the "v2" field if the given value is not nil.
func (_u *SavedLibraryUpdateOne) SetNillableV2(v *int) *SavedLibraryUpdateOne {
	if v != nil {
		_u.SetV2(*v)
	}
	return _u
}

// AddV2 adds value to the "v2" field.
func (_u *SavedLibraryUpdateOne) AddV2(v int) *SavedLibraryUpdateOne {
	_u.mutation.AddV2(v)
	return _u
}

// SetV3 sets the "v3" field.
func (_u *SavedLibraryUpdateOne) SetV3(v int) *SavedLibraryUpdateOne {
	_u.mutation.ResetV3()
	_u.mutation.SetV3(v)
	return _u
}

// SetNillableV3 sets the "v3" field if the given value is not nil.
func (_u *SavedLibraryUpdateOne) SetNillableV3(v *int) *SavedLibraryUpdateOne {
	if v != nil {
		_u.SetV3(*v)
	}
	return _u
}

// AddV3 adds value to the "v3" field.
func (_u *SavedLibraryUpdateOne) AddV3(v int) *SavedLibraryUpdateOne {
	_u.mutation.AddV3(v)
	return _u
}

// SetIsPublished sets the "isPublished" field.
func (_u *SavedLibraryUpdateOne) SetIsPublished(v bool) *SavedLibraryUpdateOne {
	_u.mutation.SetIsPublished(v)
	return _u
}

// SetNillableIsPublished sets the "isPublished" field if the given value is not nil.
func (_u *SavedLibraryUpdateOne) SetNillableIsPublished(v *bool) *SavedLibraryUpdateOne {
	if v != nil {
		_u.SetIsPublished(*v)
	}
	return _u
}

// Mutation returns the SavedLibraryMutation object of the builder.
func (_u *SavedLibraryUpdateOne) Mutation() *SavedLibraryMutation {
	return _u.mutation
}

// Where appends a list predicates to the SavedLibraryUpdate builder.
func (_u *SavedLibraryUpdateOne) Where(ps ...predicate.SavedLibrary) *SavedLibraryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SavedLibraryUpdateOne) Select(field string, fields ...string) *SavedLibraryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SavedLibrary entity.
func (_u *SavedLibraryUpdateOne) Save(ctx context.Context) (*SavedLibrary, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SavedLibraryUpdateOne) SaveX(ctx context.Context) *SavedLibrary {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SavedLibraryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SavedLibraryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SavedLibraryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := savedlibrary.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SavedLibraryUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := savedlibrary.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "SavedLibrary.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := savedlibrary.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SavedLibrary.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Version(); ok {
		if err := savedlibrary.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "SavedLibrary.version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := savedlibrary.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SavedLibrary.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.V1(); ok {
		if err := savedlibrary.V1Validator(v); err != nil {
			return &ValidationError{Name: "v1", err: fmt.Errorf(`ent: validator failed for field "SavedLibrary.v1": %w`, err)}
		}
	}
	if v, ok := _u.mutation.V2(); ok {
		if err := savedlibrary.V2Validator(v); err != nil {
			return &ValidationError{Name: "v2", err: fmt.Errorf(`ent: validator failed for field "SavedLibrary.v2": %w`, err)}
		}
	}
	if v, ok := _u.mutation.V3(); ok {
		if err := savedlibrary.V3Validator(v); err != nil {
			return &ValidationError{Name: "v3", err: fmt.Errorf(`ent: validator failed for field "SavedLibrary.v3": %w`, err)}
		}
	}
	return nil
}

func (_u *SavedLibraryUpdateOne) sqlSave(ctx context.Context) (_node *SavedLibrary, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(savedlibrary.Table, savedlibrary.Columns, sqlgraph.NewFieldSpec(savedlibrary.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SavedLibrary.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, savedlibrary.FieldID)
		for _, f := range fields {
			if !savedlibrary.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != savedlibrary.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(savedlibrary.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(savedlibrary.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(savedlibrary.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(savedlibrary.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(savedlibrary.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.V1(); ok {
		_spec.SetField(savedlibrary.FieldV1, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedV1(); ok {
		_spec.AddField(savedlibrary.FieldV1, field.TypeInt, value)
	}
	if value, ok := _u.mutation.V2(); ok {
		_spec.SetField(savedlibrary.FieldV2, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedV2(); ok {
		_spec.AddField(savedlibrary.FieldV2, field.TypeInt, value)
	}
	if value, ok := _u.mutation.V3(); ok {
		_spec.SetField(savedlibrary.FieldV3, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedV3(); ok {
		_spec.AddField(savedlibrary.FieldV3, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsPublished(); ok {
		_spec.SetField(savedlibrary.FieldIsPublished, field.TypeBool, value)
	}
	_node = &SavedLibrary{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{savedlibrary.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
