// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// RequestedLibrary is the predicate function for requestedlibrary builders.
type RequestedLibrary func(*sql.Selector)

// SavedLibrary is the predicate function for savedlibrary builders.
type SavedLibrary func(*sql.Selector)
