// Code generated by ent, DO NOT EDIT.

package savedlibrary

import (
	"time"
	"web_app/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldEQ(FieldName, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldEQ(FieldVersion, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldEQ(FieldUpdatedAt, v))
}

// V1 applies equality check predicate on the "v1" field. It's identical to V1EQ.
func V1(v int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldEQ(FieldV1, v))
}

// V2 applies equality check predicate on the "v2" field. It's identical to V2EQ.
func V2(v int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldEQ(FieldV2, v))
}

// V3 applies equality check predicate on the "v3" field. It's identical to V3EQ.
func V3(v int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldEQ(FieldV3, v))
}

// IsPublished applies equality check predicate on the "isPublished" field. It's identical to IsPublishedEQ.
func IsPublished(v bool) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldEQ(FieldIsPublished, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldContainsFold(FieldName, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "version" field.
func VersionContains(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "version" field.
func VersionHasPrefix(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "version" field.
func VersionHasSuffix(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "version" field.
func VersionEqualFold(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "version" field.
func VersionContainsFold(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldContainsFold(FieldVersion, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldLTE(FieldUpdatedAt, v))
}

// V1EQ applies the EQ predicate on the "v1" field.
func V1EQ(v int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldEQ(FieldV1, v))
}

// V1NEQ applies the NEQ predicate on the "v1" field.
func V1NEQ(v int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldNEQ(FieldV1, v))
}

// V1In applies the In predicate on the "v1" field.
func V1In(vs ...int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldIn(FieldV1, vs...))
}

// V1NotIn applies the NotIn predicate on the "v1" field.
func V1NotIn(vs ...int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldNotIn(FieldV1, vs...))
}

// V1GT applies the GT predicate on the "v1" field.
func V1GT(v int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldGT(FieldV1, v))
}

// V1GTE applies the GTE predicate on the "v1" field.
func V1GTE(v int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldGTE(FieldV1, v))
}

// V1LT applies the LT predicate on the "v1" field.
func V1LT(v int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldLT(FieldV1, v))
}

// V1LTE applies the LTE predicate on the "v1" field.
func V1LTE(v int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldLTE(FieldV1, v))
}

// V2EQ applies the EQ predicate on the "v2" field.
func V2EQ(v int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldEQ(FieldV2, v))
}

// V2NEQ applies the NEQ predicate on the "v2" field.
func V2NEQ(v int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldNEQ(FieldV2, v))
}

// V2In applies the In predicate on the "v2" field.
func V2In(vs ...int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldIn(FieldV2, vs...))
}

// V2NotIn applies the NotIn predicate on the "v2" field.
func V2NotIn(vs ...int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldNotIn(FieldV2, vs...))
}

// V2GT applies the GT predicate on the "v2" field.
func V2GT(v int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldGT(FieldV2, v))
}

// V2GTE applies the GTE predicate on the "v2" field.
func V2GTE(v int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldGTE(FieldV2, v))
}

// V2LT applies the LT predicate on the "v2" field.
func V2LT(v int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldLT(FieldV2, v))
}

// V2LTE applies the LTE predicate on the "v2" field.
func V2LTE(v int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldLTE(FieldV2, v))
}

// V3EQ applies the EQ predicate on the "v3" field.
func V3EQ(v int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldEQ(FieldV3, v))
}

// V3NEQ applies the NEQ predicate on the "v3" field.
func V3NEQ(v int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldNEQ(FieldV3, v))
}

// V3In applies the In predicate on the "v3" field.
func V3In(vs ...int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldIn(FieldV3, vs...))
}

// V3NotIn applies the NotIn predicate on the "v3" field.
func V3NotIn(vs ...int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldNotIn(FieldV3, vs...))
}

// V3GT applies the GT predicate on the "v3" field.
func V3GT(v int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldGT(FieldV3, v))
}

// V3GTE applies the GTE predicate on the "v3" field.
func V3GTE(v int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldGTE(FieldV3, v))
}

// V3LT applies the LT predicate on the "v3" field.
func V3LT(v int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldLT(FieldV3, v))
}

// V3LTE applies the LTE predicate on the "v3" field.
func V3LTE(v int) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldLTE(FieldV3, v))
}

// IsPublishedEQ applies the EQ predicate on the "isPublished" field.
func IsPublishedEQ(v bool) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldEQ(FieldIsPublished, v))
}

// IsPublishedNEQ applies the NEQ predicate on the "isPublished" field.
func IsPublishedNEQ(v bool) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.FieldNEQ(FieldIsPublished, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SavedLibrary) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SavedLibrary) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SavedLibrary) predicate.SavedLibrary {
	return predicate.SavedLibrary(sql.NotPredicates(p))
}
