// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GroupsColumns holds the columns for the "groups" table.
	GroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "is_for_user", Type: field.TypeBool},
		{Name: "requested_by", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GroupsTable holds the schema information for the "groups" table.
	GroupsTable = &schema.Table{
		Name:       "groups",
		Columns:    GroupsColumns,
		PrimaryKey: []*schema.Column{GroupsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "groups_name_is_for_user",
				Unique:  true,
				Columns: []*schema.Column{GroupsColumns[1], GroupsColumns[2]},
			},
		},
	}
	// RequestedLibrariesColumns holds the columns for the "requested_libraries" table.
	RequestedLibrariesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "kind", Type: field.TypeString},
		{Name: "version", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "uploading"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "requested_by", Type: field.TypeString},
	}
	// RequestedLibrariesTable holds the schema information for the "requested_libraries" table.
	RequestedLibrariesTable = &schema.Table{
		Name:       "requested_libraries",
		Columns:    RequestedLibrariesColumns,
		PrimaryKey: []*schema.Column{RequestedLibrariesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "requested_libraries_kind_name_version_idx",
				Unique:  true,
				Columns: []*schema.Column{RequestedLibrariesColumns[1], RequestedLibrariesColumns[6], RequestedLibrariesColumns[2]},
			},
		},
	}
	// SavedLibrariesColumns holds the columns for the "saved_libraries" table.
	SavedLibrariesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "kind", Type: field.TypeString},
		{Name: "version", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "uploading"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "full_name", Type: field.TypeString},
		{Name: "simple_name", Type: field.TypeString},
		{Name: "v1", Type: field.TypeInt},
		{Name: "v2", Type: field.TypeInt},
		{Name: "v3", Type: field.TypeInt},
		{Name: "is_published", Type: field.TypeBool, Default: false},
	}
	// SavedLibrariesTable holds the schema information for the "saved_libraries" table.
	SavedLibrariesTable = &schema.Table{
		Name:       "saved_libraries",
		Columns:    SavedLibrariesColumns,
		PrimaryKey: []*schema.Column{SavedLibrariesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "saved_libraries_kind_full_name_version_idx",
				Unique:  true,
				Columns: []*schema.Column{SavedLibrariesColumns[1], SavedLibrariesColumns[6], SavedLibrariesColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GroupsTable,
		RequestedLibrariesTable,
		SavedLibrariesTable,
	}
)

func init() {
}
